{% set python_min = "3.10" %}
{% set name = "hatchling" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatchling-{{ version }}.tar.gz
  sha256: 4d50b02aece6892b8cd0b3ce6c82cb218594d3ec5836dbde75bf41a21ab004c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hatchling = hatchling.cli:hatchling

requirements:
  host:
    - pip
    - python {{ python_min }}
    # bootstrapping
    - packaging >=24.2
    - pathspec >=0.10.1
    - pluggy >=1.0.0
    - tomli >=1.2.2
    - trove-classifiers
  run:
    - python >={{ python_min }}
    - editables >=0.3
    - importlib-metadata
    - packaging >=24.2
    - pathspec >=0.10.1
    - pluggy >=1.0.0
    - python >=3.7
    - tomli >=1.2.2
    - trove-classifiers

test:
  imports:
    - hatchling
  commands:
    - pip check
    - hatchling --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python build backend
  dev_url: https://github.com/pypa/hatch/tree/master/backend
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
