{% set name = "hatchling" %}
{% set version = "1.22.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatchling-{{ version }}.tar.gz
  sha256: ca260a5adad376563dcd5df799e79ec1d5c0a3be41e2fbe335613c451772b09e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatchling = hatchling.cli:hatchling

requirements:
  host:
    - pip
    - python >=3.7
    # bootstrapping
    - packaging >=21.3
    - pathspec >=0.10.1
    - pluggy >=1.0.0
    - tomli >=2.0
    - trove-classifiers
  run:
    - editables >=0.3
    - importlib-metadata
    - packaging >=21.3
    - pathspec >=0.10.1
    - pluggy >=1.0.0
    - python >=3.7
    - tomli >=1.2.2
    - trove-classifiers

test:
  imports:
    - hatchling
  commands:
    - pip check
    - hatchling --help
  requires:
    - pip

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python build backend
  dev_url: https://github.com/pypa/hatch/tree/master/backend
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
