{% set name = "hatchling" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatchling-{{ version }}.tar.gz
  sha256: 89d6f8332877d506095bb6acf7609ceb3cf2555703305975789a257f2ad2308c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatchling = hatchling.cli:hatchling

requirements:
  host:
    - pip
    - python >=3.7
    # bootstrapping
    - packaging >=21.3
    - pathspec >=0.9
    - pluggy >=1.0.0
    - tomli >=2.0
  run:
    - editables >=0.3
    - importlib-metadata
    - packaging >=21.3
    - pathspec >=0.9
    - pluggy >=1.0.0
    - python >=3.7
    - tomli >=1.2.2

test:
  imports:
    - hatchling
  commands:
    - pip check
    - hatchling --help
  requires:
    - pip

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python build backend
  dev_url: https://github.com/pypa/hatch/tree/master/backend
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
