{% set name = "hatchling" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatchling-{{ version }}.tar.gz
  sha256: daef0cf555a30f2e98cb295c0ac324c66fc66f33c95ea03cb79e1536b1e1f492

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatchling = hatchling.cli:hatchling

requirements:
  host:
    - pip
    - python >=3.7
    # bootstrapping
    - packaging >=21.3
    - pathspec >=0.9
    - pluggy >=1.0.0
    - tomli >=2.0
  run:
    - editables >=0.3
    - importlib-metadata
    - packaging >=21.3
    - pathspec >=0.9
    - pluggy >=1.0.0
    - python >=3.7
    - tomli >=1.2.2

test:
  imports:
    - hatchling
  commands:
    - pip check
    - hatchling --help
  requires:
    - pip

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python build backend
  dev_url: https://github.com/pypa/hatch/tree/master/backend
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
