{% set name = "hatchling" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatchling-{{ version }}.tar.gz
  sha256: 942b34e454ce3be5b03139e0a198ba8ebc08a6095d345fe829b1ae92e9326c2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatchling = hatchling.cli:hatchling

requirements:
  host:
    - pip
    - python >=3.7
    # bootstrapping
    - packaging >=21.3
    - pathspec >=0.9
    - pluggy >=1.0.0
    - tomli >=2.0
  run:
    - editables >=0.2
    - importlib-metadata
    - packaging >=21.3
    - pathspec >=0.9
    - pluggy >=1.0.0
    - python >=3.7
    - tomli >=2.0

test:
  imports:
    - hatchling
  commands:
    - pip check
    - hatchling --help
  requires:
    - pip

about:
  home: https://ofek.dev/hatch/latest/
  summary: Modern, extensible Python build backend
  dev_url: https://github.com/ofek/hatch/tree/master/backend
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
